### PR TITLE
Sync automatically campaign between speakout and civi

### PR DESCRIPTION
**Pull request by scardinius**

### CODE REVIEW

**Comment by glilienthal** [comment]
Why do we have en_US as default language? We'd want en_UK, don't we?

**Comment by tttp** [comment]
Mostly because it's the default from elsewhere, and I don't think we'll ever write differently to contacts in en_US and en_GB, but it's more correct indeed.

@scardinius, can you change?

**Comment by scardinius** [comment]
@tttp @glilienthal Yes, I can change default language in this extension. 

We have a lot of contacts with en_US value, change?

**Comment by tttp** [comment]
yes, en_US is the default, you can convert the existing ones to en_UK while
we are at it indeed

**Comment by scardinius** [comment]
@glilienthal @tttp done, preferred language changed from `en_US` into `en_GB`

**Pull request merged**
